[tools]
aws-sam = "latest"
buf = "latest"
bun = "latest"
"cargo:bat" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
deno = "latest"
go = "latest"
golangci-lint = "latest"
marksman = "latest"
node = "latest"
python = "latest"
rust = "latest"
task = "latest"
terraform = "latest"
tree-sitter = "latest"
